// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://mezgyosajeqnrxdxhaxx.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im1lemd5b3NhamVxbnJ4ZHhoYXh4Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3Mzg0NjEyOTUsImV4cCI6MjA1NDAzNzI5NX0.TGhR3NkqTTrD9Mu-Q6ZHPUHlKqmb5Gi4vUW81lI-c1w";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);